export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        {/* <h1>Hello World</h1> */}
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
